name: password_manager
description: "Password manager"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  auto_injector: ^2.0.5
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  google_sign_in: ^6.2.2
  localization: ^2.1.1
  shared_preferences: ^2.4.0
  url_launcher: ^6.3.1
  provider: ^6.1.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "lib/assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - lib/i18n/
    - lib/assets/
